### ISSUE TITLE
What is the default temperature in Kelvin?

### ISSUE THREAD

**Issue by stratosgear** [hyprwm/hyprsunset#12]
I would like to write a script that gradually alters the temperature of the screen.

In order to do so I will need to find the gradual distance from the base/default temperature to the one I finally want to set.

But your utility talks about an identity matrix as a base reference for a default value.

I'll also provide an example:

* Assuming I want to set my temperature at 4000 Kelvin right on sunset (let's assume at 18:00), with a ramp up time of 30 minutes.
* If I knew that the base/default temperature was 6000 Kelvin, then at 17:45 (15 minutes before 18:00), I should be half way between 6000 and 4000, which is (6000-4000)/2 = 5000 K
* But not having a value of 6000, or base temperature, I cannot create a smooth ramp.

Do you have any ideas how something like that can be achieved?

Thanks!

**Comment by vaxerski** [comment]
```
static Mat3x3 matrixForKelvin(unsigned long long temp) {
    float r = 1.F, g = 1.F, b = 1.F;

    temp /= 100;

    if (temp <= 66) {
        r = 255;
        g = std::clamp(99.4708025861 * std::log(temp) - 161.1195681661, 0.0, 255.0);
        if (temp <= 19)
            b = 0;
        else
            b = std::clamp(std::log(temp - 10) * 138.5177312231 - 305.0447927307, 0.0, 255.0);
    } else {
        r = std::clamp(329.698727446 * (std::pow(temp - 60, -0.1332047592)), 0.0, 255.0);
        g = std::clamp(288.1221695283 * (std::pow(temp - 60, -0.0755148492)), 0.0, 255.0);
        b = 255;
    }

    return std::array<float, 9>{r / 255.F, 0, 0, 0, g / 255.F, 0, 0, 0, b / 255.F};
}
```

reversing this, the whitepoint is about 6500 - 6600K

**Comment by stratosgear** [comment]
Reversing should result in one value, no?  Unless any value between 6500-6600, is "close-enough"...?

From my manual trial and errors, I see that there is some rounding/losses somewhere that prevents you from getting at exactly the identity matrix.  Best I could work it out was any value between 6600 and 6699 resulting in:

```
1 0 0
0 1 0
0 0 0.9903443
```

Which leads me to believe that the actual base value should be ≈ 6650K

**Comment by vaxerski** [comment]
maybe, yea. Close enough. Use the identity `hyprsunset -i` then switch to 6650 and go from there

**Comment by stratosgear** [comment]
Yep, I already started using 6650 as the default value.

I'll try to post the script when done!

Closing!

**Comment by danielwerg** [comment]
> I'll try to post the script when done!

Would love to see the script!
