### ISSUE TITLE
[REQ] A flag to specify a transition time

### ISSUE THREAD

**Issue by alba4k** [hyprwm/hyprsunset#2]
It would be nice, and fitting for a compositor that aims to be easy on the eye like hyprland is, to be able to set a "transition" time instead of having the screen immediately change temperature.

I suppose it could default zero and require a set amount of ms (100 ms could also be a reasonable default)

It would also be cool to be able to set a custom animation, e.g. switching between a linear and a cubic interpolation? Shouldn't be too hard to calculate

**Comment by vaxerski** [comment]
the current idea is to add a configurable temperatures for the time:
```
temp = identity, 16:00
temp = 3000, 22:00
temp = 3000, 4:00
temp = identity, 8:00
```

**Comment by alba4k** [comment]
not really what I'm referring to here?

I was talking about being able to animate the transition between one temperature and the next

**Comment by vaxerski** [comment]
this will make the transition gradual between 16:00 - 22:00 and 4:00 - 8:00 in this scenario.

I know you mean begin/end. yes.

**Comment by alba4k** [comment]
> this will make the transition gradual between 16:00 - 22:00 and 4:00 - 8:00 in this scenario.

Oh cool, I thought you meant it would just be scheduled. that seems quite cool ngl

**Comment by leon-erd** [comment]
Is this already implemented or just an idea for the future?

**Comment by alba4k** [comment]
None of this has been implemented yet.

**Comment by alba4k** [comment]
I suppose this is adressed by `render:ctm_animation` in hl

**Comment by leon-erd** [comment]
Is there any option to specify the fade time? Would be nice to have a transition over 2hrs for example and not only 1sec :D

**Comment by alba4k** [comment]
I don't think so

**Comment by leon-erd** [comment]
Then maybe reopen the issue. I think the functionality that most people are looking for is a gradual change of temperature during sunrise/sunset over maybe 2hrs instead of just a 1sec fade.

**Comment by alba4k** [comment]
I think https://github.com/hyprwm/hyprsunset/issues/8 is more appropriate then
