### ISSUE TITLE
[REQ] run as daemon

### ISSUE THREAD

**Issue by littleblack111** [hyprwm/hyprsunset#4]
run it via sth like -d and act something like gammastep or redshift, run in background and use something like geoclue2 to get geolocation and apply the tempreture accordingly

**Comment by vaxerski** [comment]
`hyprsunset & disown`

**Comment by littleblack111** [comment]
no. that just permanently sets it to whatever temperature. I want it to be not as warm or disabled during day time, and only enable at night

**Comment by vaxerski** [comment]
then you're not asking for a daemon but for ipc

**Comment by littleblack111** [comment]
Idk, but that's how the other ones work
