### ISSUE TITLE
Every time I run the program it creates a new process

### ISSUE THREAD

**Issue by M4rti21** [hyprwm/hyprsunset#5]
Im not sure if im doing something wrong, but i have this 3 binds on my `hyprland.conf`:
```conf
bind = $modc, N, exec, hyprsunset -t 2500
bind = $mod , N, exec, hyprsunset -t 4500
bind = $mods, N, exec, hyprsunset -t 6000
```
and every time i press the key a new process is spawned, if i check `btop` i can see hyprsunset running for every time i pressed the command, is there a "deamon" mode or a flag i should be using instead?

**Comment by vaxerski** [comment]
`killall hyprsunset ; hyprsunset -t 2500`

**Comment by M4rti21** [comment]
this works, but the tint goes away for a split second in between the older process being killed and the new process started, which feels like a blue light flashbang :/

**Comment by vaxerski** [comment]
until hyprsunset can be ran as a daemon, just try to blink I guess

**Comment by M4rti21** [comment]
yea its no big deal! if a "deamon-mode" is on the works/planned then all good here :+1:
